#ifndef TEXT_H
#define TEXT_H

typedef enum {
    TEXT_MENU_HISTORIA = 0,
    TEXT_MENU_EXTRA,
    TEXT_MENU_HIGH_SCORES,
    TEXT_MENU_OPCIONES,
    TEXT_MENU_DEBUG,
    TEXT_MENU_SALIR,
    TEXT_GAME_TITLE,
    TEXT_TITLE_OPTIONS,
    TEXT_PRESS_KEY,
    TEXT_PROGRAMMED_BY,
    TEXT_SELECT_YEAR_TITLE,
    TEXT_ESC_BACK,
    TEXT_ENTER_SELECT,
    TEXT_OPTIONS_DIFFICULTY,
    TEXT_OPTIONS_SOUND,
    TEXT_OPTIONS_SPEED,
    TEXT_OPTIONS_INPUT,
    TEXT_OPTIONS_BACK,
    TEXT_DIFFICULTY_EASY,
    TEXT_DIFFICULTY_NORMAL,
    TEXT_DIFFICULTY_HARD,
    TEXT_SOUND_ON,
    TEXT_SOUND_OFF,
    TEXT_SPEED_NORMAL,
    TEXT_SPEED_TURBO,
    TEXT_INPUT_KEYBOARD,
    TEXT_INPUT_JOYSTICK,
    TEXT_OPTIONS_FOOTER,
    TEXT_EXTRA_FOOTER,
    TEXT_JOYSTICK_NOT_FOUND,
    TEXT_OPTIONS_SAVE_FAILED,
    TEXT_COUNT
} TextId;

extern char game_title[32];

const char *text_get(TextId id);

#endif
